name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: GitHub downloads  C# code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: GitHub logs into  Docker Hub account using the  hidden secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 3: GitHub builds the Docker image and uploads it to my account
      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: hala280/my-dotnet-api:latest